image: ubuntu:xenial

stages:
  # - test
  - zip
  - deploy

# .test: &test_job
#   stage: test
#   tags:
#     - docker
#   script:
#     - cd testcases
#     - ./runtests.sh "${release}"

# test:R2017b:
#   variables:
#     release: "R2017b"
#   <<: *test_job

# test:R2018a:
#   variables:
#     release: "R2018a"
#   <<: *test_job

# test:R2018b:
#   variables:
#     release: "R2018b"
#   <<: *test_job

Code:
  stage: zip
  only:
    - master
  tags:
    - docker
  before_script:
    - apt update && apt install git
  script:
    - 'version_file=$(ls version*)'
    - 'version=${version_file#version}'
    - git archive --format zip --output "kmat.2017_or_more.v$version.zip" HEAD
  artifacts:
    name: "kmat.b$CI_JOB_ID"
    expire_in: 1 week
    paths:
      - "kmat.*.zip"

# Deploy code to RC development box
To Spack and Packages:
  stage: deploy
  only:
    - master
  tags:
    - apps
    - production
    - ubuntu18.04
  dependencies:
    - Code
  script:
    - sudo ./.pull.changes /sw/workstations/matlab/kmat_2017a_or_more
    - 'version_file=$(ls version*)'
    - 'version=${version_file#version}'
    - cp "kmat.2017_or_more.v$version.zip" /sw/packages/kmat
