image: kcr.kaust.edu.sa/os/ubuntu:xenial

stages:
  - test
  - deploy

.test: &test_job
  stage: test
  tags:
    - docker
  script:
    - cd testcases
    - ./runtests.sh "${release}"

test:R2017b:
  variables:
    release: "R2017b"
  <<: *test_job

test:R2018a:
  variables:
    release: "R2018a"
  <<: *test_job

# test:R2018b:
#   variables:
#     release: "R2018b"
#   <<: *test_job

deploy:zip:
  stage: deploy
  only:
    - master
  tags:
    - docker
  script:
    - 'version_file=$(ls version*)'
    - 'version=${version_file#version}'
    - git archive --format zip --output "kmat.2017_or_more.v$version.zip" master
  artifacts:
    name: "kmat.b$CI_JOB_ID"
    paths:
      - "kmat.*.zip"

# Deploy code to RC development box
deploy:code:
  stage: deploy
  only:
    - master
  tags:
    - devapps
  script:
    - sudo ./.pull.changes /opt/share/matlab/common/kmat2017
    - sudo ./.pull.changes /sw/workstations/apps/linux-ubuntu16.04-x86_64/matlab/kmat_2017a_or_more
